SELECT 
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :serialSputumBacilloscopy and retired = 0) AND value_coded IS NOT NULL THEN 1 ELSE 0 END) as sputum,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :serialSputumBacilloscopy and retired = 0) AND value_coded=(select DISTINCT concept_id from concept where uuid = :positive and retired = 0) THEN 1 ELSE 0 END) as sputumPositive,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :malaria and retired = 0) AND value_coded IN ( (select DISTINCT concept_id from concept where uuid = :positive and retired = 0) , (select DISTINCT concept_id from concept where uuid = :negative and retired = 0) , (select DISTINCT concept_id from concept where uuid = :indeterminate and retired = 0))  THEN 1 ELSE 0 END) as malariaRapid,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :malaria and retired = 0) AND value_coded = (select DISTINCT concept_id from concept where uuid = :positive and retired = 0) THEN 1 ELSE 0 END) as malariaRapidPositive,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :malaria and retired = 0) AND value_coded IN ((select DISTINCT concept_id from concept where uuid = :zero and retired = 0) , (select DISTINCT concept_id from concept where uuid = :onePlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :twoPlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :threePlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :fourPlus and retired = 0)) THEN 1 ELSE 0 END) as malariaMicro,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :malaria and retired = 0) AND value_coded IN ((select DISTINCT concept_id from concept where uuid = :onePlus and retired = 0)  , (select DISTINCT concept_id from concept where uuid = :twoPlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :threePlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :fourPlus and retired = 0)) THEN 1 ELSE 0 END) as malariaMicroPositive,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :malaria and retired = 0) AND value_coded IS NOT NULL THEN 1 ELSE 0 END) as malariaTotal,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :malaria and retired = 0) AND value_coded IN ((select DISTINCT concept_id from concept where uuid = :positive and retired = 0) , (select DISTINCT concept_id from concept where uuid = :onePlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :twoPlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :threePlus and retired = 0) , (select DISTINCT concept_id from concept where uuid = :fourPlus and retired = 0)) THEN 1 ELSE 0 END) as malariaPositive,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :completeBloodCount and retired = 0) and visit_type.uuid= :prenatalVisitType THEN 1 ELSE 0 END) as CBC,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :sicklingTest and retired = 0) AND value_coded IS NOT NULL and visit_type.uuid= :prenatalVisitType THEN 1 ELSE 0 END) as sickling,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :sicklingTest and retired = 0) AND value_coded=(select DISTINCT concept_id from concept where uuid = :positive and retired = 0) and visit_type.uuid= :prenatalVisitType THEN 1 ELSE 0 END) as sicklingPositive,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :bloodGroup and retired = 0) AND value_coded IS NOT NULL and visit_type.uuid= :prenatalVisitType THEN 1 ELSE 0 END) as bloodGroup,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :urinalysis and retired = 0) and visit_type.uuid= :prenatalVisitType THEN 1 ELSE 0 END) as urinalysis,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :sicklingTest and retired = 0) AND value_coded IS NOT NULL and visit_type.uuid<> :prenatalVisitType THEN 1 ELSE 0 END) as otherSickling,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :sicklingTest and retired = 0) AND value_coded=(select DISTINCT concept_id from concept where uuid = :positive and retired = 0) and visit_type.uuid<> :prenatalVisitType THEN 1 ELSE 0 END) as otherSicklingPositive,
sum(CASE WHEN concept_id=(select DISTINCT concept_id from concept where uuid = :bloodGroup and retired = 0) AND value_coded IS NOT NULL and visit_type.uuid<> :prenatalVisitType THEN 1 ELSE 0 END) as otherbloodGroup
FROM obs inner join encounter ON obs.encounter_id=encounter.encounter_id inner join visit ON  encounter.visit_id=visit.visit_id inner join visit_type ON visit.visit_type_id=visit_type.visit_type_id
where obs.voided = 0 
AND date(obs.obs_datetime) BETWEEN :startDate AND :endDate ;
