name: Deploy to GitHub Packages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 8
          cache: maven
          server-id: github
          server-username: path-drc-bot
          server-password: MAVEN_TOKEN

      - name: Deploy to GitHub Packages
        run: mvn clean deploy -B -DskipTests
        env:
          MAVEN_TOKEN: ${{ secrets.PATH_DRC_TOKEN }}
